appearance:
  color: black
  name: "PrusaPrint \U0001F609"
webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
plugins:
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo service octoprint restart
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
temperature:
  profiles:
  - bed: 100
    extruder: '255'
    name: ABS
  - bed: 60
    extruder: '215'
    name: PLA
  - bed: 100
    extruder: '220'
    name: HIPS
  - bed: 100
    extruder: '254'
    name: PP
  - bed: 85
    extruder: '230'
    name: PET
  - bed: 50
    extruder: '240'
    name: FLEX
printerProfiles:
  default: _default
serial:
  additionalPorts:
  - /dev/ttyAMA0
  autoconnect: true
  baudrate: 115200
  port: /dev/ttyAMA0
